/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AttestationHostFixletService } from "../attestationHostFixlet.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AttestationHostFixletCreateInput } from "./AttestationHostFixletCreateInput";
import { AttestationHostFixlet } from "./AttestationHostFixlet";
import { AttestationHostFixletFindManyArgs } from "./AttestationHostFixletFindManyArgs";
import { AttestationHostFixletWhereUniqueInput } from "./AttestationHostFixletWhereUniqueInput";
import { AttestationHostFixletUpdateInput } from "./AttestationHostFixletUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AttestationHostFixletControllerBase {
  constructor(
    protected readonly service: AttestationHostFixletService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AttestationHostFixlet })
  @nestAccessControl.UseRoles({
    resource: "AttestationHostFixlet",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAttestationHostFixlet(
    @common.Body() data: AttestationHostFixletCreateInput
  ): Promise<AttestationHostFixlet> {
    return await this.service.createAttestationHostFixlet({
      data: {
        ...data,

        attestationHost: {
          connect: data.attestationHost,
        },

        patchChannelFixlet: {
          connect: data.patchChannelFixlet,
        },
      },
      select: {
        attestationHost: {
          select: {
            id: true,
          },
        },

        checklistId: true,
        checklistName: true,
        created: true,
        id: true,
        name: true,

        patchChannelFixlet: {
          select: {
            id: true,
          },
        },

        tssSpec: true,
        updated: true,
        updatedBy: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AttestationHostFixlet] })
  @ApiNestedQuery(AttestationHostFixletFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AttestationHostFixlet",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async attestationHostFixlets(
    @common.Req() request: Request
  ): Promise<AttestationHostFixlet[]> {
    const args = plainToClass(AttestationHostFixletFindManyArgs, request.query);
    return this.service.attestationHostFixlets({
      ...args,
      select: {
        attestationHost: {
          select: {
            id: true,
          },
        },

        checklistId: true,
        checklistName: true,
        created: true,
        id: true,
        name: true,

        patchChannelFixlet: {
          select: {
            id: true,
          },
        },

        tssSpec: true,
        updated: true,
        updatedBy: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AttestationHostFixlet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AttestationHostFixlet",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async attestationHostFixlet(
    @common.Param() params: AttestationHostFixletWhereUniqueInput
  ): Promise<AttestationHostFixlet | null> {
    const result = await this.service.attestationHostFixlet({
      where: params,
      select: {
        attestationHost: {
          select: {
            id: true,
          },
        },

        checklistId: true,
        checklistName: true,
        created: true,
        id: true,
        name: true,

        patchChannelFixlet: {
          select: {
            id: true,
          },
        },

        tssSpec: true,
        updated: true,
        updatedBy: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AttestationHostFixlet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AttestationHostFixlet",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAttestationHostFixlet(
    @common.Param() params: AttestationHostFixletWhereUniqueInput,
    @common.Body() data: AttestationHostFixletUpdateInput
  ): Promise<AttestationHostFixlet | null> {
    try {
      return await this.service.updateAttestationHostFixlet({
        where: params,
        data: {
          ...data,

          attestationHost: {
            connect: data.attestationHost,
          },

          patchChannelFixlet: {
            connect: data.patchChannelFixlet,
          },
        },
        select: {
          attestationHost: {
            select: {
              id: true,
            },
          },

          checklistId: true,
          checklistName: true,
          created: true,
          id: true,
          name: true,

          patchChannelFixlet: {
            select: {
              id: true,
            },
          },

          tssSpec: true,
          updated: true,
          updatedBy: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AttestationHostFixlet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AttestationHostFixlet",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAttestationHostFixlet(
    @common.Param() params: AttestationHostFixletWhereUniqueInput
  ): Promise<AttestationHostFixlet | null> {
    try {
      return await this.service.deleteAttestationHostFixlet({
        where: params,
        select: {
          attestationHost: {
            select: {
              id: true,
            },
          },

          checklistId: true,
          checklistName: true,
          created: true,
          id: true,
          name: true,

          patchChannelFixlet: {
            select: {
              id: true,
            },
          },

          tssSpec: true,
          updated: true,
          updatedBy: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
