/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  AssetSupportVendor as PrismaAssetSupportVendor,
  AssetSupportDetail as PrismaAssetSupportDetail,
} from "@prisma/client";

export class AssetSupportVendorServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AssetSupportVendorCountArgs, "select">
  ): Promise<number> {
    return this.prisma.assetSupportVendor.count(args);
  }

  async assetSupportVendors(
    args: Prisma.AssetSupportVendorFindManyArgs
  ): Promise<PrismaAssetSupportVendor[]> {
    return this.prisma.assetSupportVendor.findMany(args);
  }
  async assetSupportVendor(
    args: Prisma.AssetSupportVendorFindUniqueArgs
  ): Promise<PrismaAssetSupportVendor | null> {
    return this.prisma.assetSupportVendor.findUnique(args);
  }
  async createAssetSupportVendor(
    args: Prisma.AssetSupportVendorCreateArgs
  ): Promise<PrismaAssetSupportVendor> {
    return this.prisma.assetSupportVendor.create(args);
  }
  async updateAssetSupportVendor(
    args: Prisma.AssetSupportVendorUpdateArgs
  ): Promise<PrismaAssetSupportVendor> {
    return this.prisma.assetSupportVendor.update(args);
  }
  async deleteAssetSupportVendor(
    args: Prisma.AssetSupportVendorDeleteArgs
  ): Promise<PrismaAssetSupportVendor> {
    return this.prisma.assetSupportVendor.delete(args);
  }

  async findAssetSupportDetails(
    parentId: number,
    args: Prisma.AssetSupportDetailFindManyArgs
  ): Promise<PrismaAssetSupportDetail[]> {
    return this.prisma.assetSupportVendor
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .assetSupportDetails(args);
  }
}
