/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { IpAddressService } from "../ipAddress.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { IpAddressCreateInput } from "./IpAddressCreateInput";
import { IpAddress } from "./IpAddress";
import { IpAddressFindManyArgs } from "./IpAddressFindManyArgs";
import { IpAddressWhereUniqueInput } from "./IpAddressWhereUniqueInput";
import { IpAddressUpdateInput } from "./IpAddressUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class IpAddressControllerBase {
  constructor(
    protected readonly service: IpAddressService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: IpAddress })
  @nestAccessControl.UseRoles({
    resource: "IpAddress",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createIpAddress(
    @common.Body() data: IpAddressCreateInput
  ): Promise<IpAddress> {
    return await this.service.createIpAddress({
      data: {
        ...data,

        asset: data.asset
          ? {
              connect: data.asset,
            }
          : undefined,

        assetNetworkDetails: data.assetNetworkDetails
          ? {
              connect: data.assetNetworkDetails,
            }
          : undefined,
      },
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        assetNetworkDetails: {
          select: {
            id: true,
          },
        },

        created: true,
        dnsName: true,
        id: true,
        ip: true,
        isPrimary: true,
        subnetPurpose: true,
        typeField: true,
        updated: true,
        updatedBy: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [IpAddress] })
  @ApiNestedQuery(IpAddressFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "IpAddress",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ipAddresses(@common.Req() request: Request): Promise<IpAddress[]> {
    const args = plainToClass(IpAddressFindManyArgs, request.query);
    return this.service.ipAddresses({
      ...args,
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        assetNetworkDetails: {
          select: {
            id: true,
          },
        },

        created: true,
        dnsName: true,
        id: true,
        ip: true,
        isPrimary: true,
        subnetPurpose: true,
        typeField: true,
        updated: true,
        updatedBy: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: IpAddress })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "IpAddress",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ipAddress(
    @common.Param() params: IpAddressWhereUniqueInput
  ): Promise<IpAddress | null> {
    const result = await this.service.ipAddress({
      where: params,
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        assetNetworkDetails: {
          select: {
            id: true,
          },
        },

        created: true,
        dnsName: true,
        id: true,
        ip: true,
        isPrimary: true,
        subnetPurpose: true,
        typeField: true,
        updated: true,
        updatedBy: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: IpAddress })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "IpAddress",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateIpAddress(
    @common.Param() params: IpAddressWhereUniqueInput,
    @common.Body() data: IpAddressUpdateInput
  ): Promise<IpAddress | null> {
    try {
      return await this.service.updateIpAddress({
        where: params,
        data: {
          ...data,

          asset: data.asset
            ? {
                connect: data.asset,
              }
            : undefined,

          assetNetworkDetails: data.assetNetworkDetails
            ? {
                connect: data.assetNetworkDetails,
              }
            : undefined,
        },
        select: {
          asset: {
            select: {
              id: true,
            },
          },

          assetNetworkDetails: {
            select: {
              id: true,
            },
          },

          created: true,
          dnsName: true,
          id: true,
          ip: true,
          isPrimary: true,
          subnetPurpose: true,
          typeField: true,
          updated: true,
          updatedBy: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: IpAddress })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "IpAddress",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteIpAddress(
    @common.Param() params: IpAddressWhereUniqueInput
  ): Promise<IpAddress | null> {
    try {
      return await this.service.deleteIpAddress({
        where: params,
        select: {
          asset: {
            select: {
              id: true,
            },
          },

          assetNetworkDetails: {
            select: {
              id: true,
            },
          },

          created: true,
          dnsName: true,
          id: true,
          ip: true,
          isPrimary: true,
          subnetPurpose: true,
          typeField: true,
          updated: true,
          updatedBy: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
