import { ApplicationWhereUniqueInput } from "../application/ApplicationWhereUniqueInput";
import { AttestationHostUpdateManyWithoutAttestationsInput } from "./AttestationHostUpdateManyWithoutAttestationsInput";
import { AttestationTypeWhereUniqueInput } from "../attestationType/AttestationTypeWhereUniqueInput";

export type AttestationUpdateInput = {
  alternateContactEmail?: string | null;
  alternateContactNuid?: string | null;
  application?: ApplicationWhereUniqueInput;
  attestationHost?: AttestationHostUpdateManyWithoutAttestationsInput;
  attestationType?: AttestationTypeWhereUniqueInput;
  caseId?: string | null;
  connectedToAThirdPartySystem?: boolean;
  guid?: string;
  hasSensitiveData?: boolean;
  impactedRegion?: string | null;
  isEmergencyRequest?: boolean;
  isPermanentRequest?: boolean;
  justification?: string;
  longTermSolution?: string | null;
  mitigatingCompensatingControls?: string | null;
  owningOrganization?: string | null;
  primaryContactEmail?: string;
  primaryContactNuid?: string;
  remediationPlan?: string | null;
  remediationPlanTargetedCompletion?: Date | null;
  response?: string | null;
  riskManagementOption?: string | null;
  sentToThirdParty?: Date | null;
  status?: string;
  updatedBy?: string;
};
