/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  Max,
  IsOptional,
  ValidateNested,
  IsString,
  MaxLength,
} from "class-validator";
import { AssetWhereUniqueInput } from "../../asset/base/AssetWhereUniqueInput";
import { Type } from "class-transformer";
import { BigfixRequestTypeWhereUniqueInput } from "../../bigfixRequestType/base/BigfixRequestTypeWhereUniqueInput";
import { SubMgmtChangeLogCreateNestedManyWithoutBigfixRequestsInput } from "./SubMgmtChangeLogCreateNestedManyWithoutBigfixRequestsInput";
import { TssChangeLogCreateNestedManyWithoutBigfixRequestsInput } from "./TssChangeLogCreateNestedManyWithoutBigfixRequestsInput";

@InputType()
class BigfixRequestCreateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  actionScriptId?: number | null;

  @ApiProperty({
    required: false,
    type: () => AssetWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AssetWhereUniqueInput)
  @IsOptional()
  @Field(() => AssetWhereUniqueInput, {
    nullable: true,
  })
  asset?: AssetWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @Field(() => Number)
  bigfixEnvironment!: number;

  @ApiProperty({
    required: false,
    type: () => BigfixRequestTypeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => BigfixRequestTypeWhereUniqueInput)
  @IsOptional()
  @Field(() => BigfixRequestTypeWhereUniqueInput, {
    nullable: true,
  })
  bigfixRequestType?: BigfixRequestTypeWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  computerId?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  computerStatus?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  httpResponse?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  httpResponseMessage?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  request?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  requestComputerSettings?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  requestStatus!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  response?: string | null;

  @ApiProperty({
    required: false,
    type: () => SubMgmtChangeLogCreateNestedManyWithoutBigfixRequestsInput,
  })
  @ValidateNested()
  @Type(() => SubMgmtChangeLogCreateNestedManyWithoutBigfixRequestsInput)
  @IsOptional()
  @Field(() => SubMgmtChangeLogCreateNestedManyWithoutBigfixRequestsInput, {
    nullable: true,
  })
  subMgmtChangeLog?: SubMgmtChangeLogCreateNestedManyWithoutBigfixRequestsInput;

  @ApiProperty({
    required: false,
    type: () => TssChangeLogCreateNestedManyWithoutBigfixRequestsInput,
  })
  @ValidateNested()
  @Type(() => TssChangeLogCreateNestedManyWithoutBigfixRequestsInput)
  @IsOptional()
  @Field(() => TssChangeLogCreateNestedManyWithoutBigfixRequestsInput, {
    nullable: true,
  })
  tssChangeLog?: TssChangeLogCreateNestedManyWithoutBigfixRequestsInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  updatedBy!: string;
}

export { BigfixRequestCreateInput as BigfixRequestCreateInput };
