/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  Max,
  IsOptional,
  ValidateNested,
  IsString,
  MaxLength,
} from "class-validator";
import { AssetWhereUniqueInput } from "../../asset/base/AssetWhereUniqueInput";
import { Type } from "class-transformer";
import { BigfixRequestTypeWhereUniqueInput } from "../../bigfixRequestType/base/BigfixRequestTypeWhereUniqueInput";
import { SubMgmtChangeLogUpdateManyWithoutBigfixRequestsInput } from "./SubMgmtChangeLogUpdateManyWithoutBigfixRequestsInput";
import { TssChangeLogUpdateManyWithoutBigfixRequestsInput } from "./TssChangeLogUpdateManyWithoutBigfixRequestsInput";

@InputType()
class BigfixRequestUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  actionScriptId?: number | null;

  @ApiProperty({
    required: false,
    type: () => AssetWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AssetWhereUniqueInput)
  @IsOptional()
  @Field(() => AssetWhereUniqueInput, {
    nullable: true,
  })
  asset?: AssetWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  bigfixEnvironment?: number;

  @ApiProperty({
    required: false,
    type: () => BigfixRequestTypeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => BigfixRequestTypeWhereUniqueInput)
  @IsOptional()
  @Field(() => BigfixRequestTypeWhereUniqueInput, {
    nullable: true,
  })
  bigfixRequestType?: BigfixRequestTypeWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  computerId?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  computerStatus?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  httpResponse?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  httpResponseMessage?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  request?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  requestComputerSettings?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  requestStatus?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  response?: string | null;

  @ApiProperty({
    required: false,
    type: () => SubMgmtChangeLogUpdateManyWithoutBigfixRequestsInput,
  })
  @ValidateNested()
  @Type(() => SubMgmtChangeLogUpdateManyWithoutBigfixRequestsInput)
  @IsOptional()
  @Field(() => SubMgmtChangeLogUpdateManyWithoutBigfixRequestsInput, {
    nullable: true,
  })
  subMgmtChangeLog?: SubMgmtChangeLogUpdateManyWithoutBigfixRequestsInput;

  @ApiProperty({
    required: false,
    type: () => TssChangeLogUpdateManyWithoutBigfixRequestsInput,
  })
  @ValidateNested()
  @Type(() => TssChangeLogUpdateManyWithoutBigfixRequestsInput)
  @IsOptional()
  @Field(() => TssChangeLogUpdateManyWithoutBigfixRequestsInput, {
    nullable: true,
  })
  tssChangeLog?: TssChangeLogUpdateManyWithoutBigfixRequestsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  updatedBy?: string;
}

export { BigfixRequestUpdateInput as BigfixRequestUpdateInput };
