/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AssetLocationDetailService } from "../assetLocationDetail.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AssetLocationDetailCreateInput } from "./AssetLocationDetailCreateInput";
import { AssetLocationDetail } from "./AssetLocationDetail";
import { AssetLocationDetailFindManyArgs } from "./AssetLocationDetailFindManyArgs";
import { AssetLocationDetailWhereUniqueInput } from "./AssetLocationDetailWhereUniqueInput";
import { AssetLocationDetailUpdateInput } from "./AssetLocationDetailUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AssetLocationDetailControllerBase {
  constructor(
    protected readonly service: AssetLocationDetailService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AssetLocationDetail })
  @nestAccessControl.UseRoles({
    resource: "AssetLocationDetail",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAssetLocationDetail(
    @common.Body() data: AssetLocationDetailCreateInput
  ): Promise<AssetLocationDetail> {
    return await this.service.createAssetLocationDetail({
      data: {
        ...data,

        asset: data.asset
          ? {
              connect: data.asset,
            }
          : undefined,
      },
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        created: true,
        id: true,
        inDataCenter: true,
        locationBuilding: true,
        locationCode: true,
        locationFloor: true,
        locationFull: true,
        locationGrid: true,
        locationPhysical: true,
        region: true,
        serviceArea: true,
        updated: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AssetLocationDetail] })
  @ApiNestedQuery(AssetLocationDetailFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AssetLocationDetail",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async assetLocationDetails(
    @common.Req() request: Request
  ): Promise<AssetLocationDetail[]> {
    const args = plainToClass(AssetLocationDetailFindManyArgs, request.query);
    return this.service.assetLocationDetails({
      ...args,
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        created: true,
        id: true,
        inDataCenter: true,
        locationBuilding: true,
        locationCode: true,
        locationFloor: true,
        locationFull: true,
        locationGrid: true,
        locationPhysical: true,
        region: true,
        serviceArea: true,
        updated: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AssetLocationDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AssetLocationDetail",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async assetLocationDetail(
    @common.Param() params: AssetLocationDetailWhereUniqueInput
  ): Promise<AssetLocationDetail | null> {
    const result = await this.service.assetLocationDetail({
      where: params,
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        created: true,
        id: true,
        inDataCenter: true,
        locationBuilding: true,
        locationCode: true,
        locationFloor: true,
        locationFull: true,
        locationGrid: true,
        locationPhysical: true,
        region: true,
        serviceArea: true,
        updated: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AssetLocationDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AssetLocationDetail",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAssetLocationDetail(
    @common.Param() params: AssetLocationDetailWhereUniqueInput,
    @common.Body() data: AssetLocationDetailUpdateInput
  ): Promise<AssetLocationDetail | null> {
    try {
      return await this.service.updateAssetLocationDetail({
        where: params,
        data: {
          ...data,

          asset: data.asset
            ? {
                connect: data.asset,
              }
            : undefined,
        },
        select: {
          asset: {
            select: {
              id: true,
            },
          },

          created: true,
          id: true,
          inDataCenter: true,
          locationBuilding: true,
          locationCode: true,
          locationFloor: true,
          locationFull: true,
          locationGrid: true,
          locationPhysical: true,
          region: true,
          serviceArea: true,
          updated: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AssetLocationDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AssetLocationDetail",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAssetLocationDetail(
    @common.Param() params: AssetLocationDetailWhereUniqueInput
  ): Promise<AssetLocationDetail | null> {
    try {
      return await this.service.deleteAssetLocationDetail({
        where: params,
        select: {
          asset: {
            select: {
              id: true,
            },
          },

          created: true,
          id: true,
          inDataCenter: true,
          locationBuilding: true,
          locationCode: true,
          locationFloor: true,
          locationFull: true,
          locationGrid: true,
          locationPhysical: true,
          region: true,
          serviceArea: true,
          updated: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
