/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { KeyFieldMetricService } from "../keyFieldMetric.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { KeyFieldMetricCreateInput } from "./KeyFieldMetricCreateInput";
import { KeyFieldMetric } from "./KeyFieldMetric";
import { KeyFieldMetricFindManyArgs } from "./KeyFieldMetricFindManyArgs";
import { KeyFieldMetricWhereUniqueInput } from "./KeyFieldMetricWhereUniqueInput";
import { KeyFieldMetricUpdateInput } from "./KeyFieldMetricUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class KeyFieldMetricControllerBase {
  constructor(
    protected readonly service: KeyFieldMetricService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: KeyFieldMetric })
  @nestAccessControl.UseRoles({
    resource: "KeyFieldMetric",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createKeyFieldMetric(
    @common.Body() data: KeyFieldMetricCreateInput
  ): Promise<KeyFieldMetric> {
    return await this.service.createKeyFieldMetric({
      data: data,
      select: {
        columnName: true,
        columnValue: true,
        created: true,
        errorIfPercentChangeExceeds: true,
        id: true,
        lastPassedValidation: true,
        note: true,
        statisticOperation: true,
        tableName: true,
        updated: true,
        updatedBy: true,
        valueCount: true,
        warnIfPercentChangeExceeds: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [KeyFieldMetric] })
  @ApiNestedQuery(KeyFieldMetricFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "KeyFieldMetric",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async keyFieldMetrics(
    @common.Req() request: Request
  ): Promise<KeyFieldMetric[]> {
    const args = plainToClass(KeyFieldMetricFindManyArgs, request.query);
    return this.service.keyFieldMetrics({
      ...args,
      select: {
        columnName: true,
        columnValue: true,
        created: true,
        errorIfPercentChangeExceeds: true,
        id: true,
        lastPassedValidation: true,
        note: true,
        statisticOperation: true,
        tableName: true,
        updated: true,
        updatedBy: true,
        valueCount: true,
        warnIfPercentChangeExceeds: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: KeyFieldMetric })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "KeyFieldMetric",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async keyFieldMetric(
    @common.Param() params: KeyFieldMetricWhereUniqueInput
  ): Promise<KeyFieldMetric | null> {
    const result = await this.service.keyFieldMetric({
      where: params,
      select: {
        columnName: true,
        columnValue: true,
        created: true,
        errorIfPercentChangeExceeds: true,
        id: true,
        lastPassedValidation: true,
        note: true,
        statisticOperation: true,
        tableName: true,
        updated: true,
        updatedBy: true,
        valueCount: true,
        warnIfPercentChangeExceeds: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: KeyFieldMetric })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "KeyFieldMetric",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateKeyFieldMetric(
    @common.Param() params: KeyFieldMetricWhereUniqueInput,
    @common.Body() data: KeyFieldMetricUpdateInput
  ): Promise<KeyFieldMetric | null> {
    try {
      return await this.service.updateKeyFieldMetric({
        where: params,
        data: data,
        select: {
          columnName: true,
          columnValue: true,
          created: true,
          errorIfPercentChangeExceeds: true,
          id: true,
          lastPassedValidation: true,
          note: true,
          statisticOperation: true,
          tableName: true,
          updated: true,
          updatedBy: true,
          valueCount: true,
          warnIfPercentChangeExceeds: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: KeyFieldMetric })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "KeyFieldMetric",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteKeyFieldMetric(
    @common.Param() params: KeyFieldMetricWhereUniqueInput
  ): Promise<KeyFieldMetric | null> {
    try {
      return await this.service.deleteKeyFieldMetric({
        where: params,
        select: {
          columnName: true,
          columnValue: true,
          created: true,
          errorIfPercentChangeExceeds: true,
          id: true,
          lastPassedValidation: true,
          note: true,
          statisticOperation: true,
          tableName: true,
          updated: true,
          updatedBy: true,
          valueCount: true,
          warnIfPercentChangeExceeds: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
