import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { ApplicationContactListRelationFilter } from "../applicationContact/ApplicationContactListRelationFilter";
import { ApplicationDeploymentListRelationFilter } from "../applicationDeployment/ApplicationDeploymentListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { ApplicationLifecycleDetailListRelationFilter } from "../applicationLifecycleDetail/ApplicationLifecycleDetailListRelationFilter";
import { ApplicationOrganizationListRelationFilter } from "../applicationOrganization/ApplicationOrganizationListRelationFilter";
import { ApplicationSupportDetailListRelationFilter } from "../applicationSupportDetail/ApplicationSupportDetailListRelationFilter";
import { AttestationListRelationFilter } from "../attestation/AttestationListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { IntFilter } from "../../util/IntFilter";

export type ApplicationWhereInput = {
  accessesInternet?: BooleanNullableFilter;
  applicationContact?: ApplicationContactListRelationFilter;
  applicationDeployment?: ApplicationDeploymentListRelationFilter;
  applicationId?: StringFilter;
  applicationLifecycleDetails?: ApplicationLifecycleDetailListRelationFilter;
  applicationOrganization?: ApplicationOrganizationListRelationFilter;
  applicationSupportDetails?: ApplicationSupportDetailListRelationFilter;
  attestation?: AttestationListRelationFilter;
  businessName?: StringNullableFilter;
  category?: StringNullableFilter;
  confidentialityRating?: StringNullableFilter;
  created?: DateTimeFilter;
  description?: StringNullableFilter;
  hasPersonalConfidentialInfo?: BooleanNullableFilter;
  hasProtectedHealthInfo?: BooleanNullableFilter;
  id?: IntFilter;
  isLifeSustaining?: BooleanNullableFilter;
  isSubjectToPciCompliance?: BooleanNullableFilter;
  isSubjectToSoxCompliance?: BooleanNullableFilter;
  name?: StringNullableFilter;
  overrideServerValidation?: StringNullableFilter;
  shortName?: StringNullableFilter;
  status?: StringNullableFilter;
  subCategory?: StringNullableFilter;
  updated?: DateTimeFilter;
  updatedBy?: StringFilter;
  version?: StringNullableFilter;
  websiteUrl?: StringNullableFilter;
};
