/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  Max,
  IsOptional,
  ValidateNested,
  IsString,
  MaxLength,
  IsBoolean,
} from "class-validator";
import { GraphQLBigInt } from "../../util/GraphQLBigInt";
import { ApplicationDeploymentUpdateManyWithoutAssetsInput } from "./ApplicationDeploymentUpdateManyWithoutAssetsInput";
import { Type } from "class-transformer";
import { AssetConfigurationDetailUpdateManyWithoutAssetsInput } from "./AssetConfigurationDetailUpdateManyWithoutAssetsInput";
import { AssetLocationDetailUpdateManyWithoutAssetsInput } from "./AssetLocationDetailUpdateManyWithoutAssetsInput";
import { AssetNetworkDetailUpdateManyWithoutAssetsInput } from "./AssetNetworkDetailUpdateManyWithoutAssetsInput";
import { AssetSupportDetailUpdateManyWithoutAssetsInput } from "./AssetSupportDetailUpdateManyWithoutAssetsInput";
import { AttestationHostUpdateManyWithoutAssetsInput } from "./AttestationHostUpdateManyWithoutAssetsInput";
import { BigfixRequestUpdateManyWithoutAssetsInput } from "./BigfixRequestUpdateManyWithoutAssetsInput";
import { DatasourceDeviceUpdateManyWithoutAssetsInput } from "./DatasourceDeviceUpdateManyWithoutAssetsInput";
import { EndpointManagementSolutionWhereUniqueInput } from "../../endpointManagementSolution/base/EndpointManagementSolutionWhereUniqueInput";
import { ExceptionUpdateManyWithoutAssetsInput } from "./ExceptionUpdateManyWithoutAssetsInput";
import { IpAddressUpdateManyWithoutAssetsInput } from "./IpAddressUpdateManyWithoutAssetsInput";
import { MaintenanceWindowUpdateManyWithoutAssetsInput } from "./MaintenanceWindowUpdateManyWithoutAssetsInput";
import { OperationsCalendarUpdateManyWithoutAssetsInput } from "./OperationsCalendarUpdateManyWithoutAssetsInput";
import { RebootWindowUpdateManyWithoutAssetsInput } from "./RebootWindowUpdateManyWithoutAssetsInput";
import { SubMgmtChangeLogUpdateManyWithoutAssetsInput } from "./SubMgmtChangeLogUpdateManyWithoutAssetsInput";
import { TssChangeLogUpdateManyWithoutAssetsInput } from "./TssChangeLogUpdateManyWithoutAssetsInput";

@InputType()
class AssetUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => GraphQLBigInt, {
    nullable: true,
  })
  altId?: bigint | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  appServerId?: number | null;

  @ApiProperty({
    required: false,
    type: () => ApplicationDeploymentUpdateManyWithoutAssetsInput,
  })
  @ValidateNested()
  @Type(() => ApplicationDeploymentUpdateManyWithoutAssetsInput)
  @IsOptional()
  @Field(() => ApplicationDeploymentUpdateManyWithoutAssetsInput, {
    nullable: true,
  })
  applicationDeployment?: ApplicationDeploymentUpdateManyWithoutAssetsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => GraphQLBigInt, {
    nullable: true,
  })
  applicationHostId?: bigint | null;

  @ApiProperty({
    required: false,
    type: () => AssetConfigurationDetailUpdateManyWithoutAssetsInput,
  })
  @ValidateNested()
  @Type(() => AssetConfigurationDetailUpdateManyWithoutAssetsInput)
  @IsOptional()
  @Field(() => AssetConfigurationDetailUpdateManyWithoutAssetsInput, {
    nullable: true,
  })
  assetConfigurationDetails?: AssetConfigurationDetailUpdateManyWithoutAssetsInput;

  @ApiProperty({
    required: false,
    type: () => AssetLocationDetailUpdateManyWithoutAssetsInput,
  })
  @ValidateNested()
  @Type(() => AssetLocationDetailUpdateManyWithoutAssetsInput)
  @IsOptional()
  @Field(() => AssetLocationDetailUpdateManyWithoutAssetsInput, {
    nullable: true,
  })
  assetLocationDetails?: AssetLocationDetailUpdateManyWithoutAssetsInput;

  @ApiProperty({
    required: false,
    type: () => AssetNetworkDetailUpdateManyWithoutAssetsInput,
  })
  @ValidateNested()
  @Type(() => AssetNetworkDetailUpdateManyWithoutAssetsInput)
  @IsOptional()
  @Field(() => AssetNetworkDetailUpdateManyWithoutAssetsInput, {
    nullable: true,
  })
  assetNetworkDetails?: AssetNetworkDetailUpdateManyWithoutAssetsInput;

  @ApiProperty({
    required: false,
    type: () => AssetSupportDetailUpdateManyWithoutAssetsInput,
  })
  @ValidateNested()
  @Type(() => AssetSupportDetailUpdateManyWithoutAssetsInput)
  @IsOptional()
  @Field(() => AssetSupportDetailUpdateManyWithoutAssetsInput, {
    nullable: true,
  })
  assetSupportDetails?: AssetSupportDetailUpdateManyWithoutAssetsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  assigned?: string | null;

  @ApiProperty({
    required: false,
    type: () => AttestationHostUpdateManyWithoutAssetsInput,
  })
  @ValidateNested()
  @Type(() => AttestationHostUpdateManyWithoutAssetsInput)
  @IsOptional()
  @Field(() => AttestationHostUpdateManyWithoutAssetsInput, {
    nullable: true,
  })
  attestationHost?: AttestationHostUpdateManyWithoutAssetsInput;

  @ApiProperty({
    required: false,
    type: () => BigfixRequestUpdateManyWithoutAssetsInput,
  })
  @ValidateNested()
  @Type(() => BigfixRequestUpdateManyWithoutAssetsInput)
  @IsOptional()
  @Field(() => BigfixRequestUpdateManyWithoutAssetsInput, {
    nullable: true,
  })
  bigfixRequest?: BigfixRequestUpdateManyWithoutAssetsInput;

  @ApiProperty({
    required: false,
    type: () => DatasourceDeviceUpdateManyWithoutAssetsInput,
  })
  @ValidateNested()
  @Type(() => DatasourceDeviceUpdateManyWithoutAssetsInput)
  @IsOptional()
  @Field(() => DatasourceDeviceUpdateManyWithoutAssetsInput, {
    nullable: true,
  })
  datasourceDevices?: DatasourceDeviceUpdateManyWithoutAssetsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => EndpointManagementSolutionWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => EndpointManagementSolutionWhereUniqueInput)
  @IsOptional()
  @Field(() => EndpointManagementSolutionWhereUniqueInput, {
    nullable: true,
  })
  endpointManagementSolution?: EndpointManagementSolutionWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  enterpriseId?: string | null;

  @ApiProperty({
    required: false,
    type: () => ExceptionUpdateManyWithoutAssetsInput,
  })
  @ValidateNested()
  @Type(() => ExceptionUpdateManyWithoutAssetsInput)
  @IsOptional()
  @Field(() => ExceptionUpdateManyWithoutAssetsInput, {
    nullable: true,
  })
  exception?: ExceptionUpdateManyWithoutAssetsInput;

  @ApiProperty({
    required: false,
    type: () => IpAddressUpdateManyWithoutAssetsInput,
  })
  @ValidateNested()
  @Type(() => IpAddressUpdateManyWithoutAssetsInput)
  @IsOptional()
  @Field(() => IpAddressUpdateManyWithoutAssetsInput, {
    nullable: true,
  })
  ipAddress?: IpAddressUpdateManyWithoutAssetsInput;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isLocked?: boolean | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isShared?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => MaintenanceWindowUpdateManyWithoutAssetsInput,
  })
  @ValidateNested()
  @Type(() => MaintenanceWindowUpdateManyWithoutAssetsInput)
  @IsOptional()
  @Field(() => MaintenanceWindowUpdateManyWithoutAssetsInput, {
    nullable: true,
  })
  maintenanceWindow?: MaintenanceWindowUpdateManyWithoutAssetsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  note?: string | null;

  @ApiProperty({
    required: false,
    type: () => OperationsCalendarUpdateManyWithoutAssetsInput,
  })
  @ValidateNested()
  @Type(() => OperationsCalendarUpdateManyWithoutAssetsInput)
  @IsOptional()
  @Field(() => OperationsCalendarUpdateManyWithoutAssetsInput, {
    nullable: true,
  })
  operationsCalendar?: OperationsCalendarUpdateManyWithoutAssetsInput;

  @ApiProperty({
    required: false,
    type: () => RebootWindowUpdateManyWithoutAssetsInput,
  })
  @ValidateNested()
  @Type(() => RebootWindowUpdateManyWithoutAssetsInput)
  @IsOptional()
  @Field(() => RebootWindowUpdateManyWithoutAssetsInput, {
    nullable: true,
  })
  rebootWindow?: RebootWindowUpdateManyWithoutAssetsInput;

  @ApiProperty({
    required: false,
    type: () => SubMgmtChangeLogUpdateManyWithoutAssetsInput,
  })
  @ValidateNested()
  @Type(() => SubMgmtChangeLogUpdateManyWithoutAssetsInput)
  @IsOptional()
  @Field(() => SubMgmtChangeLogUpdateManyWithoutAssetsInput, {
    nullable: true,
  })
  subMgmtChangeLog?: SubMgmtChangeLogUpdateManyWithoutAssetsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  systemBackupId?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  systemCitrixId?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  tag?: string | null;

  @ApiProperty({
    required: false,
    type: () => TssChangeLogUpdateManyWithoutAssetsInput,
  })
  @ValidateNested()
  @Type(() => TssChangeLogUpdateManyWithoutAssetsInput)
  @IsOptional()
  @Field(() => TssChangeLogUpdateManyWithoutAssetsInput, {
    nullable: true,
  })
  tssChangeLog?: TssChangeLogUpdateManyWithoutAssetsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  updatedBy?: string;
}

export { AssetUpdateInput as AssetUpdateInput };
