/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { EnvironmentService } from "../environment.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EnvironmentCreateInput } from "./EnvironmentCreateInput";
import { Environment } from "./Environment";
import { EnvironmentFindManyArgs } from "./EnvironmentFindManyArgs";
import { EnvironmentWhereUniqueInput } from "./EnvironmentWhereUniqueInput";
import { EnvironmentUpdateInput } from "./EnvironmentUpdateInput";
import { EndpointManagementSolutionFindManyArgs } from "../../endpointManagementSolution/base/EndpointManagementSolutionFindManyArgs";
import { EndpointManagementSolution } from "../../endpointManagementSolution/base/EndpointManagementSolution";
import { EndpointManagementSolutionWhereUniqueInput } from "../../endpointManagementSolution/base/EndpointManagementSolutionWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class EnvironmentControllerBase {
  constructor(
    protected readonly service: EnvironmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Environment })
  @nestAccessControl.UseRoles({
    resource: "Environment",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createEnvironment(
    @common.Body() data: EnvironmentCreateInput
  ): Promise<Environment> {
    return await this.service.createEnvironment({
      data: data,
      select: {
        environmentDesc: true,
        environmentName: true,
        id: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Environment] })
  @ApiNestedQuery(EnvironmentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Environment",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async environments(@common.Req() request: Request): Promise<Environment[]> {
    const args = plainToClass(EnvironmentFindManyArgs, request.query);
    return this.service.environments({
      ...args,
      select: {
        environmentDesc: true,
        environmentName: true,
        id: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Environment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Environment",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async environment(
    @common.Param() params: EnvironmentWhereUniqueInput
  ): Promise<Environment | null> {
    const result = await this.service.environment({
      where: params,
      select: {
        environmentDesc: true,
        environmentName: true,
        id: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Environment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Environment",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateEnvironment(
    @common.Param() params: EnvironmentWhereUniqueInput,
    @common.Body() data: EnvironmentUpdateInput
  ): Promise<Environment | null> {
    try {
      return await this.service.updateEnvironment({
        where: params,
        data: data,
        select: {
          environmentDesc: true,
          environmentName: true,
          id: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Environment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Environment",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteEnvironment(
    @common.Param() params: EnvironmentWhereUniqueInput
  ): Promise<Environment | null> {
    try {
      return await this.service.deleteEnvironment({
        where: params,
        select: {
          environmentDesc: true,
          environmentName: true,
          id: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/endpointManagementSolution")
  @ApiNestedQuery(EndpointManagementSolutionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "EndpointManagementSolution",
    action: "read",
    possession: "any",
  })
  async findEndpointManagementSolution(
    @common.Req() request: Request,
    @common.Param() params: EnvironmentWhereUniqueInput
  ): Promise<EndpointManagementSolution[]> {
    const query = plainToClass(
      EndpointManagementSolutionFindManyArgs,
      request.query
    );
    const results = await this.service.findEndpointManagementSolution(
      params.id,
      {
        ...query,
        select: {
          description: true,

          environment: {
            select: {
              id: true,
            },
          },

          id: true,
          name: true,
        },
      }
    );
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/endpointManagementSolution")
  @nestAccessControl.UseRoles({
    resource: "Environment",
    action: "update",
    possession: "any",
  })
  async connectEndpointManagementSolution(
    @common.Param() params: EnvironmentWhereUniqueInput,
    @common.Body() body: EndpointManagementSolutionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      endpointManagementSolution: {
        connect: body,
      },
    };
    await this.service.updateEnvironment({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/endpointManagementSolution")
  @nestAccessControl.UseRoles({
    resource: "Environment",
    action: "update",
    possession: "any",
  })
  async updateEndpointManagementSolution(
    @common.Param() params: EnvironmentWhereUniqueInput,
    @common.Body() body: EndpointManagementSolutionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      endpointManagementSolution: {
        set: body,
      },
    };
    await this.service.updateEnvironment({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/endpointManagementSolution")
  @nestAccessControl.UseRoles({
    resource: "Environment",
    action: "update",
    possession: "any",
  })
  async disconnectEndpointManagementSolution(
    @common.Param() params: EnvironmentWhereUniqueInput,
    @common.Body() body: EndpointManagementSolutionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      endpointManagementSolution: {
        disconnect: body,
      },
    };
    await this.service.updateEnvironment({
      where: params,
      data,
      select: { id: true },
    });
  }
}
