/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Environment } from "./Environment";
import { EnvironmentCountArgs } from "./EnvironmentCountArgs";
import { EnvironmentFindManyArgs } from "./EnvironmentFindManyArgs";
import { EnvironmentFindUniqueArgs } from "./EnvironmentFindUniqueArgs";
import { CreateEnvironmentArgs } from "./CreateEnvironmentArgs";
import { UpdateEnvironmentArgs } from "./UpdateEnvironmentArgs";
import { DeleteEnvironmentArgs } from "./DeleteEnvironmentArgs";
import { EndpointManagementSolutionFindManyArgs } from "../../endpointManagementSolution/base/EndpointManagementSolutionFindManyArgs";
import { EndpointManagementSolution } from "../../endpointManagementSolution/base/EndpointManagementSolution";
import { EnvironmentService } from "../environment.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Environment)
export class EnvironmentResolverBase {
  constructor(
    protected readonly service: EnvironmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Environment",
    action: "read",
    possession: "any",
  })
  async _environmentsMeta(
    @graphql.Args() args: EnvironmentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Environment])
  @nestAccessControl.UseRoles({
    resource: "Environment",
    action: "read",
    possession: "any",
  })
  async environments(
    @graphql.Args() args: EnvironmentFindManyArgs
  ): Promise<Environment[]> {
    return this.service.environments(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Environment, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Environment",
    action: "read",
    possession: "own",
  })
  async environment(
    @graphql.Args() args: EnvironmentFindUniqueArgs
  ): Promise<Environment | null> {
    const result = await this.service.environment(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Environment)
  @nestAccessControl.UseRoles({
    resource: "Environment",
    action: "create",
    possession: "any",
  })
  async createEnvironment(
    @graphql.Args() args: CreateEnvironmentArgs
  ): Promise<Environment> {
    return await this.service.createEnvironment({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Environment)
  @nestAccessControl.UseRoles({
    resource: "Environment",
    action: "update",
    possession: "any",
  })
  async updateEnvironment(
    @graphql.Args() args: UpdateEnvironmentArgs
  ): Promise<Environment | null> {
    try {
      return await this.service.updateEnvironment({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Environment)
  @nestAccessControl.UseRoles({
    resource: "Environment",
    action: "delete",
    possession: "any",
  })
  async deleteEnvironment(
    @graphql.Args() args: DeleteEnvironmentArgs
  ): Promise<Environment | null> {
    try {
      return await this.service.deleteEnvironment(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [EndpointManagementSolution], {
    name: "endpointManagementSolution",
  })
  @nestAccessControl.UseRoles({
    resource: "EndpointManagementSolution",
    action: "read",
    possession: "any",
  })
  async findEndpointManagementSolution(
    @graphql.Parent() parent: Environment,
    @graphql.Args() args: EndpointManagementSolutionFindManyArgs
  ): Promise<EndpointManagementSolution[]> {
    const results = await this.service.findEndpointManagementSolution(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }
}
