import { ApplicationDeployment } from "../applicationDeployment/ApplicationDeployment";
import { AssetConfigurationDetail } from "../assetConfigurationDetail/AssetConfigurationDetail";
import { AssetLocationDetail } from "../assetLocationDetail/AssetLocationDetail";
import { AssetNetworkDetail } from "../assetNetworkDetail/AssetNetworkDetail";
import { AssetSupportDetail } from "../assetSupportDetail/AssetSupportDetail";
import { AttestationHost } from "../attestationHost/AttestationHost";
import { BigfixRequest } from "../bigfixRequest/BigfixRequest";
import { DatasourceDevice } from "../datasourceDevice/DatasourceDevice";
import { EndpointManagementSolution } from "../endpointManagementSolution/EndpointManagementSolution";
import { Exception } from "../exception/Exception";
import { IpAddress } from "../ipAddress/IpAddress";
import { MaintenanceWindow } from "../maintenanceWindow/MaintenanceWindow";
import { OperationsCalendar } from "../operationsCalendar/OperationsCalendar";
import { RebootWindow } from "../rebootWindow/RebootWindow";
import { SubMgmtChangeLog } from "../subMgmtChangeLog/SubMgmtChangeLog";
import { TssChangeLog } from "../tssChangeLog/TssChangeLog";

export type Asset = {
  altId: bigint | null;
  appServerId: number | null;
  applicationDeployment?: Array<ApplicationDeployment>;
  applicationHostId: bigint | null;
  assetConfigurationDetails?: Array<AssetConfigurationDetail>;
  assetLocationDetails?: Array<AssetLocationDetail>;
  assetNetworkDetails?: Array<AssetNetworkDetail>;
  assetSupportDetails?: Array<AssetSupportDetail>;
  assigned: string | null;
  attestationHost?: Array<AttestationHost>;
  bigfixRequest?: Array<BigfixRequest>;
  created: Date;
  datasourceDevices?: Array<DatasourceDevice>;
  description: string | null;
  endpointManagementSolution?: EndpointManagementSolution | null;
  enterpriseId: string | null;
  exception?: Array<Exception>;
  id: bigint;
  ipAddress?: Array<IpAddress>;
  isLocked: boolean | null;
  isShared: boolean | null;
  maintenanceWindow?: Array<MaintenanceWindow>;
  note: string | null;
  operationsCalendar?: Array<OperationsCalendar>;
  rebootWindow?: Array<RebootWindow>;
  subMgmtChangeLog?: Array<SubMgmtChangeLog>;
  systemBackupId: number | null;
  systemCitrixId: number | null;
  tag: string | null;
  tssChangeLog?: Array<TssChangeLog>;
  updated: Date;
  updatedBy: string;
};
