import { ApplicationDeploymentCreateNestedManyWithoutAssetsInput } from "./ApplicationDeploymentCreateNestedManyWithoutAssetsInput";
import { AssetConfigurationDetailCreateNestedManyWithoutAssetsInput } from "./AssetConfigurationDetailCreateNestedManyWithoutAssetsInput";
import { AssetLocationDetailCreateNestedManyWithoutAssetsInput } from "./AssetLocationDetailCreateNestedManyWithoutAssetsInput";
import { AssetNetworkDetailCreateNestedManyWithoutAssetsInput } from "./AssetNetworkDetailCreateNestedManyWithoutAssetsInput";
import { AssetSupportDetailCreateNestedManyWithoutAssetsInput } from "./AssetSupportDetailCreateNestedManyWithoutAssetsInput";
import { AttestationHostCreateNestedManyWithoutAssetsInput } from "./AttestationHostCreateNestedManyWithoutAssetsInput";
import { BigfixRequestCreateNestedManyWithoutAssetsInput } from "./BigfixRequestCreateNestedManyWithoutAssetsInput";
import { DatasourceDeviceCreateNestedManyWithoutAssetsInput } from "./DatasourceDeviceCreateNestedManyWithoutAssetsInput";
import { EndpointManagementSolutionWhereUniqueInput } from "../endpointManagementSolution/EndpointManagementSolutionWhereUniqueInput";
import { ExceptionCreateNestedManyWithoutAssetsInput } from "./ExceptionCreateNestedManyWithoutAssetsInput";
import { IpAddressCreateNestedManyWithoutAssetsInput } from "./IpAddressCreateNestedManyWithoutAssetsInput";
import { MaintenanceWindowCreateNestedManyWithoutAssetsInput } from "./MaintenanceWindowCreateNestedManyWithoutAssetsInput";
import { OperationsCalendarCreateNestedManyWithoutAssetsInput } from "./OperationsCalendarCreateNestedManyWithoutAssetsInput";
import { RebootWindowCreateNestedManyWithoutAssetsInput } from "./RebootWindowCreateNestedManyWithoutAssetsInput";
import { SubMgmtChangeLogCreateNestedManyWithoutAssetsInput } from "./SubMgmtChangeLogCreateNestedManyWithoutAssetsInput";
import { TssChangeLogCreateNestedManyWithoutAssetsInput } from "./TssChangeLogCreateNestedManyWithoutAssetsInput";

export type AssetCreateInput = {
  altId?: bigint | null;
  appServerId?: number | null;
  applicationDeployment?: ApplicationDeploymentCreateNestedManyWithoutAssetsInput;
  applicationHostId?: bigint | null;
  assetConfigurationDetails?: AssetConfigurationDetailCreateNestedManyWithoutAssetsInput;
  assetLocationDetails?: AssetLocationDetailCreateNestedManyWithoutAssetsInput;
  assetNetworkDetails?: AssetNetworkDetailCreateNestedManyWithoutAssetsInput;
  assetSupportDetails?: AssetSupportDetailCreateNestedManyWithoutAssetsInput;
  assigned?: string | null;
  attestationHost?: AttestationHostCreateNestedManyWithoutAssetsInput;
  bigfixRequest?: BigfixRequestCreateNestedManyWithoutAssetsInput;
  datasourceDevices?: DatasourceDeviceCreateNestedManyWithoutAssetsInput;
  description?: string | null;
  endpointManagementSolution?: EndpointManagementSolutionWhereUniqueInput | null;
  enterpriseId?: string | null;
  exception?: ExceptionCreateNestedManyWithoutAssetsInput;
  ipAddress?: IpAddressCreateNestedManyWithoutAssetsInput;
  isLocked?: boolean | null;
  isShared?: boolean | null;
  maintenanceWindow?: MaintenanceWindowCreateNestedManyWithoutAssetsInput;
  note?: string | null;
  operationsCalendar?: OperationsCalendarCreateNestedManyWithoutAssetsInput;
  rebootWindow?: RebootWindowCreateNestedManyWithoutAssetsInput;
  subMgmtChangeLog?: SubMgmtChangeLogCreateNestedManyWithoutAssetsInput;
  systemBackupId?: number | null;
  systemCitrixId?: number | null;
  tag?: string | null;
  tssChangeLog?: TssChangeLogCreateNestedManyWithoutAssetsInput;
  updatedBy: string;
};
