import { BigIntNullableFilter } from "../../util/BigIntNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { ApplicationDeploymentListRelationFilter } from "../applicationDeployment/ApplicationDeploymentListRelationFilter";
import { AssetConfigurationDetailListRelationFilter } from "../assetConfigurationDetail/AssetConfigurationDetailListRelationFilter";
import { AssetLocationDetailListRelationFilter } from "../assetLocationDetail/AssetLocationDetailListRelationFilter";
import { AssetNetworkDetailListRelationFilter } from "../assetNetworkDetail/AssetNetworkDetailListRelationFilter";
import { AssetSupportDetailListRelationFilter } from "../assetSupportDetail/AssetSupportDetailListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { AttestationHostListRelationFilter } from "../attestationHost/AttestationHostListRelationFilter";
import { BigfixRequestListRelationFilter } from "../bigfixRequest/BigfixRequestListRelationFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { DatasourceDeviceListRelationFilter } from "../datasourceDevice/DatasourceDeviceListRelationFilter";
import { EndpointManagementSolutionWhereUniqueInput } from "../endpointManagementSolution/EndpointManagementSolutionWhereUniqueInput";
import { ExceptionListRelationFilter } from "../exception/ExceptionListRelationFilter";
import { BigIntFilter } from "../../util/BigIntFilter";
import { IpAddressListRelationFilter } from "../ipAddress/IpAddressListRelationFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { MaintenanceWindowListRelationFilter } from "../maintenanceWindow/MaintenanceWindowListRelationFilter";
import { OperationsCalendarListRelationFilter } from "../operationsCalendar/OperationsCalendarListRelationFilter";
import { RebootWindowListRelationFilter } from "../rebootWindow/RebootWindowListRelationFilter";
import { SubMgmtChangeLogListRelationFilter } from "../subMgmtChangeLog/SubMgmtChangeLogListRelationFilter";
import { TssChangeLogListRelationFilter } from "../tssChangeLog/TssChangeLogListRelationFilter";
import { StringFilter } from "../../util/StringFilter";

export type AssetWhereInput = {
  altId?: BigIntNullableFilter;
  appServerId?: IntNullableFilter;
  applicationDeployment?: ApplicationDeploymentListRelationFilter;
  applicationHostId?: BigIntNullableFilter;
  assetConfigurationDetails?: AssetConfigurationDetailListRelationFilter;
  assetLocationDetails?: AssetLocationDetailListRelationFilter;
  assetNetworkDetails?: AssetNetworkDetailListRelationFilter;
  assetSupportDetails?: AssetSupportDetailListRelationFilter;
  assigned?: StringNullableFilter;
  attestationHost?: AttestationHostListRelationFilter;
  bigfixRequest?: BigfixRequestListRelationFilter;
  created?: DateTimeFilter;
  datasourceDevices?: DatasourceDeviceListRelationFilter;
  description?: StringNullableFilter;
  endpointManagementSolution?: EndpointManagementSolutionWhereUniqueInput;
  enterpriseId?: StringNullableFilter;
  exception?: ExceptionListRelationFilter;
  id?: BigIntFilter;
  ipAddress?: IpAddressListRelationFilter;
  isLocked?: BooleanNullableFilter;
  isShared?: BooleanNullableFilter;
  maintenanceWindow?: MaintenanceWindowListRelationFilter;
  note?: StringNullableFilter;
  operationsCalendar?: OperationsCalendarListRelationFilter;
  rebootWindow?: RebootWindowListRelationFilter;
  subMgmtChangeLog?: SubMgmtChangeLogListRelationFilter;
  systemBackupId?: IntNullableFilter;
  systemCitrixId?: IntNullableFilter;
  tag?: StringNullableFilter;
  tssChangeLog?: TssChangeLogListRelationFilter;
  updated?: DateTimeFilter;
  updatedBy?: StringFilter;
};
