import { ApplicationDeploymentUpdateManyWithoutAssetsInput } from "./ApplicationDeploymentUpdateManyWithoutAssetsInput";
import { AssetConfigurationDetailUpdateManyWithoutAssetsInput } from "./AssetConfigurationDetailUpdateManyWithoutAssetsInput";
import { AssetLocationDetailUpdateManyWithoutAssetsInput } from "./AssetLocationDetailUpdateManyWithoutAssetsInput";
import { AssetNetworkDetailUpdateManyWithoutAssetsInput } from "./AssetNetworkDetailUpdateManyWithoutAssetsInput";
import { AssetSupportDetailUpdateManyWithoutAssetsInput } from "./AssetSupportDetailUpdateManyWithoutAssetsInput";
import { AttestationHostUpdateManyWithoutAssetsInput } from "./AttestationHostUpdateManyWithoutAssetsInput";
import { BigfixRequestUpdateManyWithoutAssetsInput } from "./BigfixRequestUpdateManyWithoutAssetsInput";
import { DatasourceDeviceUpdateManyWithoutAssetsInput } from "./DatasourceDeviceUpdateManyWithoutAssetsInput";
import { EndpointManagementSolutionWhereUniqueInput } from "../endpointManagementSolution/EndpointManagementSolutionWhereUniqueInput";
import { ExceptionUpdateManyWithoutAssetsInput } from "./ExceptionUpdateManyWithoutAssetsInput";
import { IpAddressUpdateManyWithoutAssetsInput } from "./IpAddressUpdateManyWithoutAssetsInput";
import { MaintenanceWindowUpdateManyWithoutAssetsInput } from "./MaintenanceWindowUpdateManyWithoutAssetsInput";
import { OperationsCalendarUpdateManyWithoutAssetsInput } from "./OperationsCalendarUpdateManyWithoutAssetsInput";
import { RebootWindowUpdateManyWithoutAssetsInput } from "./RebootWindowUpdateManyWithoutAssetsInput";
import { SubMgmtChangeLogUpdateManyWithoutAssetsInput } from "./SubMgmtChangeLogUpdateManyWithoutAssetsInput";
import { TssChangeLogUpdateManyWithoutAssetsInput } from "./TssChangeLogUpdateManyWithoutAssetsInput";

export type AssetUpdateInput = {
  altId?: bigint | null;
  appServerId?: number | null;
  applicationDeployment?: ApplicationDeploymentUpdateManyWithoutAssetsInput;
  applicationHostId?: bigint | null;
  assetConfigurationDetails?: AssetConfigurationDetailUpdateManyWithoutAssetsInput;
  assetLocationDetails?: AssetLocationDetailUpdateManyWithoutAssetsInput;
  assetNetworkDetails?: AssetNetworkDetailUpdateManyWithoutAssetsInput;
  assetSupportDetails?: AssetSupportDetailUpdateManyWithoutAssetsInput;
  assigned?: string | null;
  attestationHost?: AttestationHostUpdateManyWithoutAssetsInput;
  bigfixRequest?: BigfixRequestUpdateManyWithoutAssetsInput;
  datasourceDevices?: DatasourceDeviceUpdateManyWithoutAssetsInput;
  description?: string | null;
  endpointManagementSolution?: EndpointManagementSolutionWhereUniqueInput | null;
  enterpriseId?: string | null;
  exception?: ExceptionUpdateManyWithoutAssetsInput;
  ipAddress?: IpAddressUpdateManyWithoutAssetsInput;
  isLocked?: boolean | null;
  isShared?: boolean | null;
  maintenanceWindow?: MaintenanceWindowUpdateManyWithoutAssetsInput;
  note?: string | null;
  operationsCalendar?: OperationsCalendarUpdateManyWithoutAssetsInput;
  rebootWindow?: RebootWindowUpdateManyWithoutAssetsInput;
  subMgmtChangeLog?: SubMgmtChangeLogUpdateManyWithoutAssetsInput;
  systemBackupId?: number | null;
  systemCitrixId?: number | null;
  tag?: string | null;
  tssChangeLog?: TssChangeLogUpdateManyWithoutAssetsInput;
  updatedBy?: string;
};
