/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MaintenanceWindowService } from "../maintenanceWindow.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MaintenanceWindowCreateInput } from "./MaintenanceWindowCreateInput";
import { MaintenanceWindow } from "./MaintenanceWindow";
import { MaintenanceWindowFindManyArgs } from "./MaintenanceWindowFindManyArgs";
import { MaintenanceWindowWhereUniqueInput } from "./MaintenanceWindowWhereUniqueInput";
import { MaintenanceWindowUpdateInput } from "./MaintenanceWindowUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MaintenanceWindowControllerBase {
  constructor(
    protected readonly service: MaintenanceWindowService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MaintenanceWindow })
  @nestAccessControl.UseRoles({
    resource: "MaintenanceWindow",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMaintenanceWindow(
    @common.Body() data: MaintenanceWindowCreateInput
  ): Promise<MaintenanceWindow> {
    return await this.service.createMaintenanceWindow({
      data: {
        ...data,

        asset: data.asset
          ? {
              connect: data.asset,
            }
          : undefined,
      },
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        created: true,
        id: true,
        maintWindowAvailableDayOfWeek: true,
        maintWindowAvailableMonths: true,
        maintWindowAvailableWeeksOfMonth: true,
        maintWindowCloseTime: true,
        maintWindowLastInside: true,
        maintWindowLevelOfSupport: true,
        maintWindowOpenTime: true,
        updated: true,
        updatedBy: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [MaintenanceWindow] })
  @ApiNestedQuery(MaintenanceWindowFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "MaintenanceWindow",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async maintenanceWindows(
    @common.Req() request: Request
  ): Promise<MaintenanceWindow[]> {
    const args = plainToClass(MaintenanceWindowFindManyArgs, request.query);
    return this.service.maintenanceWindows({
      ...args,
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        created: true,
        id: true,
        maintWindowAvailableDayOfWeek: true,
        maintWindowAvailableMonths: true,
        maintWindowAvailableWeeksOfMonth: true,
        maintWindowCloseTime: true,
        maintWindowLastInside: true,
        maintWindowLevelOfSupport: true,
        maintWindowOpenTime: true,
        updated: true,
        updatedBy: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MaintenanceWindow })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MaintenanceWindow",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async maintenanceWindow(
    @common.Param() params: MaintenanceWindowWhereUniqueInput
  ): Promise<MaintenanceWindow | null> {
    const result = await this.service.maintenanceWindow({
      where: params,
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        created: true,
        id: true,
        maintWindowAvailableDayOfWeek: true,
        maintWindowAvailableMonths: true,
        maintWindowAvailableWeeksOfMonth: true,
        maintWindowCloseTime: true,
        maintWindowLastInside: true,
        maintWindowLevelOfSupport: true,
        maintWindowOpenTime: true,
        updated: true,
        updatedBy: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MaintenanceWindow })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MaintenanceWindow",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMaintenanceWindow(
    @common.Param() params: MaintenanceWindowWhereUniqueInput,
    @common.Body() data: MaintenanceWindowUpdateInput
  ): Promise<MaintenanceWindow | null> {
    try {
      return await this.service.updateMaintenanceWindow({
        where: params,
        data: {
          ...data,

          asset: data.asset
            ? {
                connect: data.asset,
              }
            : undefined,
        },
        select: {
          asset: {
            select: {
              id: true,
            },
          },

          created: true,
          id: true,
          maintWindowAvailableDayOfWeek: true,
          maintWindowAvailableMonths: true,
          maintWindowAvailableWeeksOfMonth: true,
          maintWindowCloseTime: true,
          maintWindowLastInside: true,
          maintWindowLevelOfSupport: true,
          maintWindowOpenTime: true,
          updated: true,
          updatedBy: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MaintenanceWindow })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MaintenanceWindow",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMaintenanceWindow(
    @common.Param() params: MaintenanceWindowWhereUniqueInput
  ): Promise<MaintenanceWindow | null> {
    try {
      return await this.service.deleteMaintenanceWindow({
        where: params,
        select: {
          asset: {
            select: {
              id: true,
            },
          },

          created: true,
          id: true,
          maintWindowAvailableDayOfWeek: true,
          maintWindowAvailableMonths: true,
          maintWindowAvailableWeeksOfMonth: true,
          maintWindowCloseTime: true,
          maintWindowLastInside: true,
          maintWindowLevelOfSupport: true,
          maintWindowOpenTime: true,
          updated: true,
          updatedBy: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
