/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TssChangeLogService } from "../tssChangeLog.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TssChangeLogCreateInput } from "./TssChangeLogCreateInput";
import { TssChangeLog } from "./TssChangeLog";
import { TssChangeLogFindManyArgs } from "./TssChangeLogFindManyArgs";
import { TssChangeLogWhereUniqueInput } from "./TssChangeLogWhereUniqueInput";
import { TssChangeLogUpdateInput } from "./TssChangeLogUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TssChangeLogControllerBase {
  constructor(
    protected readonly service: TssChangeLogService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TssChangeLog })
  @nestAccessControl.UseRoles({
    resource: "TssChangeLog",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTssChangeLog(
    @common.Body() data: TssChangeLogCreateInput
  ): Promise<TssChangeLog> {
    return await this.service.createTssChangeLog({
      data: {
        ...data,

        asset: data.asset
          ? {
              connect: data.asset,
            }
          : undefined,

        bigfixRequest: data.bigfixRequest
          ? {
              connect: data.bigfixRequest,
            }
          : undefined,

        tssChangeLogStatus: {
          connect: data.tssChangeLogStatus,
        },
      },
      select: {
        action: true,
        applyOn: true,
        applyOnNextScheduledMaintWindow: true,

        asset: {
          select: {
            id: true,
          },
        },

        bigfixRequest: {
          select: {
            id: true,
          },
        },

        created: true,
        id: true,
        remediationWindowHours: true,

        tssChangeLogStatus: {
          select: {
            id: true,
          },
        },

        tssIncludeList: true,
        updated: true,
        updatedBy: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TssChangeLog] })
  @ApiNestedQuery(TssChangeLogFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TssChangeLog",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async tssChangeLogs(@common.Req() request: Request): Promise<TssChangeLog[]> {
    const args = plainToClass(TssChangeLogFindManyArgs, request.query);
    return this.service.tssChangeLogs({
      ...args,
      select: {
        action: true,
        applyOn: true,
        applyOnNextScheduledMaintWindow: true,

        asset: {
          select: {
            id: true,
          },
        },

        bigfixRequest: {
          select: {
            id: true,
          },
        },

        created: true,
        id: true,
        remediationWindowHours: true,

        tssChangeLogStatus: {
          select: {
            id: true,
          },
        },

        tssIncludeList: true,
        updated: true,
        updatedBy: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TssChangeLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TssChangeLog",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async tssChangeLog(
    @common.Param() params: TssChangeLogWhereUniqueInput
  ): Promise<TssChangeLog | null> {
    const result = await this.service.tssChangeLog({
      where: params,
      select: {
        action: true,
        applyOn: true,
        applyOnNextScheduledMaintWindow: true,

        asset: {
          select: {
            id: true,
          },
        },

        bigfixRequest: {
          select: {
            id: true,
          },
        },

        created: true,
        id: true,
        remediationWindowHours: true,

        tssChangeLogStatus: {
          select: {
            id: true,
          },
        },

        tssIncludeList: true,
        updated: true,
        updatedBy: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TssChangeLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TssChangeLog",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTssChangeLog(
    @common.Param() params: TssChangeLogWhereUniqueInput,
    @common.Body() data: TssChangeLogUpdateInput
  ): Promise<TssChangeLog | null> {
    try {
      return await this.service.updateTssChangeLog({
        where: params,
        data: {
          ...data,

          asset: data.asset
            ? {
                connect: data.asset,
              }
            : undefined,

          bigfixRequest: data.bigfixRequest
            ? {
                connect: data.bigfixRequest,
              }
            : undefined,

          tssChangeLogStatus: {
            connect: data.tssChangeLogStatus,
          },
        },
        select: {
          action: true,
          applyOn: true,
          applyOnNextScheduledMaintWindow: true,

          asset: {
            select: {
              id: true,
            },
          },

          bigfixRequest: {
            select: {
              id: true,
            },
          },

          created: true,
          id: true,
          remediationWindowHours: true,

          tssChangeLogStatus: {
            select: {
              id: true,
            },
          },

          tssIncludeList: true,
          updated: true,
          updatedBy: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TssChangeLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TssChangeLog",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTssChangeLog(
    @common.Param() params: TssChangeLogWhereUniqueInput
  ): Promise<TssChangeLog | null> {
    try {
      return await this.service.deleteTssChangeLog({
        where: params,
        select: {
          action: true,
          applyOn: true,
          applyOnNextScheduledMaintWindow: true,

          asset: {
            select: {
              id: true,
            },
          },

          bigfixRequest: {
            select: {
              id: true,
            },
          },

          created: true,
          id: true,
          remediationWindowHours: true,

          tssChangeLogStatus: {
            select: {
              id: true,
            },
          },

          tssIncludeList: true,
          updated: true,
          updatedBy: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
