/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsString,
  MaxLength,
  IsDate,
  IsOptional,
  IsBoolean,
  ValidateNested,
  IsInt,
  Max,
} from "class-validator";

import { Type } from "class-transformer";
import { Asset } from "../../asset/base/Asset";
import { BigfixRequest } from "../../bigfixRequest/base/BigfixRequest";
import { TssChangeLogStatus } from "../../tssChangeLogStatus/base/TssChangeLogStatus";

@ObjectType()
class TssChangeLog {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  action!: string;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  applyOn!: Date | null;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  applyOnNextScheduledMaintWindow!: boolean;

  @ApiProperty({
    required: false,
    type: () => Asset,
  })
  @ValidateNested()
  @Type(() => Asset)
  @IsOptional()
  asset?: Asset | null;

  @ApiProperty({
    required: false,
    type: () => BigfixRequest,
  })
  @ValidateNested()
  @Type(() => BigfixRequest)
  @IsOptional()
  bigfixRequest?: BigfixRequest | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  created!: Date;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  id!: number;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @Field(() => Number)
  remediationWindowHours!: number;

  @ApiProperty({
    required: true,
    type: () => TssChangeLogStatus,
  })
  @ValidateNested()
  @Type(() => TssChangeLogStatus)
  tssChangeLogStatus?: TssChangeLogStatus;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  tssIncludeList!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updated!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  updatedBy!: string;
}

export { TssChangeLog as TssChangeLog };
