/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AttestationHostService } from "../attestationHost.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AttestationHostCreateInput } from "./AttestationHostCreateInput";
import { AttestationHost } from "./AttestationHost";
import { AttestationHostFindManyArgs } from "./AttestationHostFindManyArgs";
import { AttestationHostWhereUniqueInput } from "./AttestationHostWhereUniqueInput";
import { AttestationHostUpdateInput } from "./AttestationHostUpdateInput";
import { AttestationHostFixletFindManyArgs } from "../../attestationHostFixlet/base/AttestationHostFixletFindManyArgs";
import { AttestationHostFixlet } from "../../attestationHostFixlet/base/AttestationHostFixlet";
import { AttestationHostFixletWhereUniqueInput } from "../../attestationHostFixlet/base/AttestationHostFixletWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AttestationHostControllerBase {
  constructor(
    protected readonly service: AttestationHostService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AttestationHost })
  @nestAccessControl.UseRoles({
    resource: "AttestationHost",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAttestationHost(
    @common.Body() data: AttestationHostCreateInput
  ): Promise<AttestationHost> {
    return await this.service.createAttestationHost({
      data: {
        ...data,

        asset: {
          connect: data.asset,
        },

        attestation: {
          connect: data.attestation,
        },
      },
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        attestation: {
          select: {
            id: true,
          },
        },

        created: true,
        id: true,
        isSupportedByThirdParty: true,
        updated: true,
        updatedBy: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AttestationHost] })
  @ApiNestedQuery(AttestationHostFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AttestationHost",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async attestationHosts(
    @common.Req() request: Request
  ): Promise<AttestationHost[]> {
    const args = plainToClass(AttestationHostFindManyArgs, request.query);
    return this.service.attestationHosts({
      ...args,
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        attestation: {
          select: {
            id: true,
          },
        },

        created: true,
        id: true,
        isSupportedByThirdParty: true,
        updated: true,
        updatedBy: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AttestationHost })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AttestationHost",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async attestationHost(
    @common.Param() params: AttestationHostWhereUniqueInput
  ): Promise<AttestationHost | null> {
    const result = await this.service.attestationHost({
      where: params,
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        attestation: {
          select: {
            id: true,
          },
        },

        created: true,
        id: true,
        isSupportedByThirdParty: true,
        updated: true,
        updatedBy: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AttestationHost })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AttestationHost",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAttestationHost(
    @common.Param() params: AttestationHostWhereUniqueInput,
    @common.Body() data: AttestationHostUpdateInput
  ): Promise<AttestationHost | null> {
    try {
      return await this.service.updateAttestationHost({
        where: params,
        data: {
          ...data,

          asset: {
            connect: data.asset,
          },

          attestation: {
            connect: data.attestation,
          },
        },
        select: {
          asset: {
            select: {
              id: true,
            },
          },

          attestation: {
            select: {
              id: true,
            },
          },

          created: true,
          id: true,
          isSupportedByThirdParty: true,
          updated: true,
          updatedBy: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AttestationHost })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AttestationHost",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAttestationHost(
    @common.Param() params: AttestationHostWhereUniqueInput
  ): Promise<AttestationHost | null> {
    try {
      return await this.service.deleteAttestationHost({
        where: params,
        select: {
          asset: {
            select: {
              id: true,
            },
          },

          attestation: {
            select: {
              id: true,
            },
          },

          created: true,
          id: true,
          isSupportedByThirdParty: true,
          updated: true,
          updatedBy: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/attestationHostFixlet")
  @ApiNestedQuery(AttestationHostFixletFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AttestationHostFixlet",
    action: "read",
    possession: "any",
  })
  async findAttestationHostFixlet(
    @common.Req() request: Request,
    @common.Param() params: AttestationHostWhereUniqueInput
  ): Promise<AttestationHostFixlet[]> {
    const query = plainToClass(
      AttestationHostFixletFindManyArgs,
      request.query
    );
    const results = await this.service.findAttestationHostFixlet(params.id, {
      ...query,
      select: {
        attestationHost: {
          select: {
            id: true,
          },
        },

        checklistId: true,
        checklistName: true,
        created: true,
        id: true,
        name: true,

        patchChannelFixlet: {
          select: {
            id: true,
          },
        },

        tssSpec: true,
        updated: true,
        updatedBy: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/attestationHostFixlet")
  @nestAccessControl.UseRoles({
    resource: "AttestationHost",
    action: "update",
    possession: "any",
  })
  async connectAttestationHostFixlet(
    @common.Param() params: AttestationHostWhereUniqueInput,
    @common.Body() body: AttestationHostFixletWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attestationHostFixlet: {
        connect: body,
      },
    };
    await this.service.updateAttestationHost({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/attestationHostFixlet")
  @nestAccessControl.UseRoles({
    resource: "AttestationHost",
    action: "update",
    possession: "any",
  })
  async updateAttestationHostFixlet(
    @common.Param() params: AttestationHostWhereUniqueInput,
    @common.Body() body: AttestationHostFixletWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attestationHostFixlet: {
        set: body,
      },
    };
    await this.service.updateAttestationHost({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/attestationHostFixlet")
  @nestAccessControl.UseRoles({
    resource: "AttestationHost",
    action: "update",
    possession: "any",
  })
  async disconnectAttestationHostFixlet(
    @common.Param() params: AttestationHostWhereUniqueInput,
    @common.Body() body: AttestationHostFixletWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attestationHostFixlet: {
        disconnect: body,
      },
    };
    await this.service.updateAttestationHost({
      where: params,
      data,
      select: { id: true },
    });
  }
}
