/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field, Float } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsInt,
  Max,
  IsOptional,
  ValidateNested,
  IsDate,
  IsNumber,
  IsString,
  MaxLength,
} from "class-validator";

import { Asset } from "../../asset/base/Asset";
import { Type } from "class-transformer";
import { AssetSupportVendor } from "../../assetSupportVendor/base/AssetSupportVendor";
import { GraphQLBigInt } from "../../util/GraphQLBigInt";
import { Decimal } from "decimal.js";

@ObjectType()
class AssetSupportDetail {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  activityBasedCosting!: number | null;

  @ApiProperty({
    required: false,
    type: () => Asset,
  })
  @ValidateNested()
  @Type(() => Asset)
  @IsOptional()
  asset?: Asset | null;

  @ApiProperty({
    required: false,
    type: () => AssetSupportVendor,
  })
  @ValidateNested()
  @Type(() => AssetSupportVendor)
  @IsOptional()
  assetSupportVendor?: AssetSupportVendor | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  created!: Date;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => GraphQLBigInt)
  id!: bigint;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => GraphQLBigInt, {
    nullable: true,
  })
  resourceUnitId!: bigint | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  supportContractEndDate!: Date | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  supportContractId!: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Float, {
    nullable: true,
  })
  supportContractRenewalCost!: Decimal | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  supportContractRenewalDate!: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  supportContractRenewalNotes!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  supportContractRenewalTerm!: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  supportContractStartDate!: Date | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updated!: Date;
}

export { AssetSupportDetail as AssetSupportDetail };
